### PR TITLE
feat(helm): Sidecar and Service Account Update

### PR DESCRIPTION
**Pull request by jluckett-panw**
Enable extra containers and service account customization  to facilitate running a sql auth proxy as a sidecar.  The service account customization was necessary to enable alternative authentication methods such as workload identity.

Please squash when merging.

### CODE REVIEW

**Comment by jluckett-panw** [comment]
link #507 to this PR

**Comment by burningalchemist** [comment]
There are some small linting issues for values.yaml:
```
Error: 33:25 [trailing-spaces] trailing spaces
  Error: 181:28 [new-line-at-end-of-file] no new line character at the end of file
```

**Comment by jluckett-panw** [comment]
My mistake - every pipeline is a little different.  Will push a fix now.

**Comment by burningalchemist** [comment]
Yeah, no rush. The linter is quite strict, just to make sure the helm install/upgrade tests are stable.

I guess you need to make sure the last line has a new line control character, but is not an empty line itself.

**Comment by jluckett-panw** [comment]
As many a famous developer has said "it passes on my machine now, give it a shot"
🙏

**Comment by jluckett-panw** [comment]
I should get a first MR badge from this!  I am so sorry for the trouble - my conditional wasn't complete I should've caught that.

**Comment by burningalchemist** [comment]
@jluckett-panw no worries at all, take your time. 😃👍

**Comment by jluckett-panw** [comment]
Last time today - I have manually run through your ci process on a GKE cluster and upgrades go off without a hitch?  I will not bother you again until Monday if this one doesn't work.

TIA!

**Review by burningalchemist — APPROVED** [review]
@jluckett-panw LGTM! 🚀 Thanks a lot for your contribution! 👏

**Comment by burningalchemist** [comment]
@jluckett-panw just a heads up - I've readjusted the logic for serviceAccount object creation/referencing [here](https://github.com/burningalchemist/sql_exporter/pull/513). Your changes are already released as of v0.4.6. v0.5.0 has a slightly different mechanism, so it's a breaking change.

**Pull request merged**
