### PR TITLE
Adds support to ignore_errors property

### PR DESCRIPTION
**Pull request by lneves12**
Adds ignore_errors property. This avoids breaking the whole exporter while supporting multiple versions of a database server with the same configuration

### CODE REVIEW

**Comment by burningalchemist** [comment]
Hey @lneves12, could you please bring a bit more detailed example when a query crashes the exporter? I'm curious about the case. :)

**Comment by burningalchemist** [comment]
@lneves12, could you provide some details here? :)

**Comment by burningalchemist** [comment]
I don't think we should ignore errors as it leads to unreliability.

It's possible that the errors come from a particular database driver. In this case it makes sense to fix the original problem.

I close this PR so far as there's not much activity at the moment to proceed.

**Comment by lneves12** [comment]
@burningalchemist Sorry, I missed the notifications for this. Thanks for closing, as you said this doesn't make sense anymore. We were basically using the same config for different sql versions, because our exporter deployment was kinda hacky. We decided to improve our deployment process for the exporter, so we discarded this hacky approach. 

Thanks for your time and replying to this .

**Pull request closed without merging**
