### PR TITLE
feat(helm): add an ability to mount extra volumes

### PR DESCRIPTION
**Pull request by allanger**
This is a PR that is supposed to cover both
- https://github.com/burningalchemist/sql_exporter/pull/432
- https://github.com/burningalchemist/sql_exporter/pull/397

I haven't added new tests, I think it might make sense, but I would first wait for a @burningalchemist opinion in the approach

### CODE REVIEW

**Comment by burningalchemist** [comment]
@allanger Thanks, I'll have a look today. 👍

**Review by burningalchemist — APPROVED** [review]
@allanger Looks good to me! Let's give it a shot. 🚀

**Review by burningalchemist — CHANGES_REQUESTED** [review]
Do you mind also updating the readme for `createConfig`?

**Comment by allanger** [comment]
Yes, sure, will try to do it within next couple of days

**Review by burningalchemist — APPROVED** [review]

**Pull request merged**
