### PR TITLE
fix(helm): add annotations field to Service resource

### PR DESCRIPTION
**Pull request by eugenekainara**

### CODE REVIEW

**Comment by burningalchemist** [comment]
Hey @eugenekainara, thank you for your contribution!

There's a small [ongoing issue](https://github.com/helm/chart-testing-action/issues/132) with one of the steps. Once it's fixed, we should have tests checked and annotations merged. 👍

**Comment by burningalchemist** [comment]
@eugenekainara, could you please also add some service `annotations` to the testing file [here](https://github.com/burningalchemist/sql_exporter/blob/b3d0004dc55799085e5dc52811bc44e8d517a9f5/helm/ci/postgresql-values.yaml#L9) in the meantime?

**Comment by burningalchemist** [comment]
@eugenekainara it should be available on the new chart version `v0.1.5`, please give it a try. 👍

**Comment by eugenekainara** [comment]
@burningalchemist works well. thanks!

**Pull request merged**
