### PR TITLE
feat: add ability to not prepare statements

### PR DESCRIPTION
**Pull request by fffinkel**
Add this for cases when the backend does not support it

### CODE REVIEW

**Comment by burningalchemist** [comment]
Hi @fffinkel, thanks for your PR? Could you please share a bit more details about the feature (or more the backend part)? It's just for the history and better visibility of the PR. just a few lines with an example would be perfect! :)

**Comment by fffinkel** [comment]
Hey @burningalchemist, sorry for such a delay in response! We added this feature because we connect to ProxySQL, which does not properly support prepared statements.

**Comment by fffinkel** [comment]
Thanks very much!

**Comment by srikiraju** [comment]
Oh wow, this is so timely @fffinkel, I was testing out this exporter right now for exactly the ProxySQL use case and ran into this problem and was considering whipping out a PR when I noticed this! Thanks for doing this.

**Comment by srikiraju** [comment]
any chance we can get a release on this?

**Comment by burningalchemist** [comment]
Hey @srikiraju! Apologies, I haven't received the notification to the message. I'm preparing a new release next week. 👍 Will keep you posted.

**Pull request merged**
